-- Supabase SQL setup for the static dubbing vote app.
-- Run this in Supabase Dashboard -> SQL Editor.

create table if not exists groups (
  id int primary key,
  name text default '',
  work_title text default '',
  members text default '',
  has_performed boolean default false,
  created_at timestamptz default now()
);

create table if not exists event_state (
  id int primary key,
  current_group_id int references groups(id),
  phase text default 'idle',
  voting_open boolean default false,
  voting_start_time timestamptz,
  canvassing_end_time timestamptz,
  voting_end_time timestamptz,
  show_ranking boolean default false,
  updated_at timestamptz default now()
);

create table if not exists votes (
  id bigint generated by default as identity primary key,
  group_id int not null references groups(id),
  voter_token text not null,
  score int not null check (score >= 1 and score <= 10),
  created_at timestamptz default now(),
  unique (group_id, voter_token)
);


-- If you already created the old version, run these ALTER statements once.
alter table groups add column if not exists work_title text default '';
alter table groups add column if not exists members text default '';

insert into groups (id, name)
values
(1, ''), (2, ''), (3, ''), (4, ''), (5, ''),
(6, ''), (7, ''), (8, ''), (9, ''), (10, '')
on conflict (id) do nothing;

insert into event_state (id, current_group_id, phase, voting_open, show_ranking)
values (1, null, 'idle', false, false)
on conflict (id) do nothing;

-- Simple public policies for static hosting.
-- Important: This is convenient for a school event, not secure against technical students.
-- For stricter security, use a backend or Supabase Edge Functions for admin actions.

alter table groups enable row level security;
alter table event_state enable row level security;
alter table votes enable row level security;

drop policy if exists "public read groups" on groups;
drop policy if exists "public modify groups" on groups;
drop policy if exists "public read event_state" on event_state;
drop policy if exists "public modify event_state" on event_state;
drop policy if exists "public read votes" on votes;
drop policy if exists "public insert votes" on votes;
drop policy if exists "public delete votes" on votes;

create policy "public read groups" on groups for select using (true);
create policy "public modify groups" on groups for update using (true) with check (true);

create policy "public read event_state" on event_state for select using (true);
create policy "public modify event_state" on event_state for update using (true) with check (true);

create policy "public read votes" on votes for select using (true);
create policy "public insert votes" on votes for insert with check (true);
create policy "public delete votes" on votes for delete using (true);
