-- Supabase SQL setup for the dubbing vote app.
-- Run this in Supabase Dashboard -> SQL Editor.

create table if not exists groups (
  id int primary key,
  name text default '',
  work_title text default '',
  members text default '',
  has_performed boolean default false,
  created_at timestamptz default now()
);

create table if not exists event_state (
  id int primary key,
  current_group_id int references groups(id),
  phase text default 'idle',
  voting_open boolean default false,
  voting_start_time timestamptz,
  canvassing_end_time timestamptz,
  voting_end_time timestamptz,
  show_ranking boolean default false,
  updated_at timestamptz default now()
);

create table if not exists votes (
  id bigint generated by default as identity primary key,
  group_id int not null references groups(id),
  voter_token text not null,
  score int not null check (score >= 1 and score <= 10),
  created_at timestamptz default now(),
  unique (group_id, voter_token)
);

alter table groups add column if not exists work_title text default '';
alter table groups add column if not exists members text default '';

insert into groups (id, name, work_title, members)
values
(1, '低调组', '小猪佩奇', '李峻宇、法舜哲、刘瑜董泽、邱傲然'),
(2, '企鹅组', '马达加斯加的企鹅1', '朱海滨、王鸿飞、殷子尧、吴硕宸'),
(3, '宠物王', '爱宠大机密', '王若璇、王薇茗、贾璀琦'),
(4, '探案组', '疯狂动物城', '温子豪、袁睿、王雪瑜'),
(5, '天煞队', '功夫熊猫3', '张峻瑜、郗梓淳、蒋家增'),
(6, '随便队', '神偷奶爸', '王梓安、张迎栋、周雨馨、刘小童'),
(7, 'Team Spirit', '狮子王', '金旻志、王铭洋、颜鑫宇、张晶贻'),
(8, '蔚蓝队', '阿甘正传', '王文煊、Sami'),
(9, '无人队', '奇幻森林', '闫梓翔、娄家辉')
on conflict (id) do update set
  name = excluded.name,
  work_title = excluded.work_title,
  members = excluded.members;

insert into event_state (id, current_group_id, phase, voting_open, show_ranking)
values (1, null, 'idle', false, false)
on conflict (id) do update set
  current_group_id = null,
  phase = 'idle',
  voting_open = false,
  voting_start_time = null,
  canvassing_end_time = null,
  voting_end_time = null,
  show_ranking = false,
  updated_at = now();

alter table groups enable row level security;
alter table event_state enable row level security;
alter table votes enable row level security;

drop policy if exists "public read groups" on groups;
drop policy if exists "public modify groups" on groups;
drop policy if exists "public read event_state" on event_state;
drop policy if exists "public modify event_state" on event_state;
drop policy if exists "public read votes" on votes;
drop policy if exists "public insert votes" on votes;
drop policy if exists "public delete votes" on votes;

create policy "public read groups" on groups for select using (true);
create policy "public modify groups" on groups for update using (true) with check (true);

create policy "public read event_state" on event_state for select using (true);
create policy "public modify event_state" on event_state for update using (true) with check (true);

create policy "public read votes" on votes for select using (true);
create policy "public insert votes" on votes for insert with check (true);
create policy "public delete votes" on votes for delete using (true);

-- If this is the final event database and you want to clear test votes, run:
-- delete from votes;
